### ISSUE TITLE
Can it edit(write) metadata,or in the future?

### ISSUE THREAD

**Issue by lcl1995225** [drewnoakes/metadata-extractor#465] opened 2020-03-03 14:23 UTC
It's a wonderful dependency for Java to extract metadata from images,videos. 
But how can I use it to edit metadata ,or it's possible in the future? Now I can only use pyexif2 instead.
Thanks.

**Comment by drewnoakes** [comment] 2020-04-13 21:26
Duplicate of #14.

**Closed by drewnoakes** 2020-04-13 21:26 UTC
