### ISSUE TITLE
Editing of metadata

### ISSUE THREAD

**Issue by wingers999** [drewnoakes/metadata-extractor#463] opened 2020-02-06 15:36 UTC
Firstly, great project - works really well for me

But I really need ability to edit/write some metadata to my images, even if just basic fields such as Title, Subject, Comments etc

I know it was mentioned in a previous PR but wanted to get an update as to whether this is going to be implemented at some point hopefully?

Thanks again

**Comment by drewnoakes** [comment] 2020-02-13 01:18
Thanks for your interest in the project.

As for editing metadata, there's no update here. This is a huge task and isn't scheduled.

Closing as a duplicate of #14.

**Closed by drewnoakes** 2020-02-13 01:18 UTC

**Comment by wingers999** [comment] 2020-02-13 01:26
Okay thanks, have found another project which seems to do what I needed in relation of editing the data - for anyone else reading this = https://github.com/oozcitak/exiflibrary
