### ISSUE TITLE
General way to get height/width

### ISSUE THREAD

**Issue by Pitometsu** [drewnoakes/metadata-extractor#380] opened 2018-11-30 20:25 UTC
Is there any way to get height/width in general, like `FileTypeDetector.detectFileType` does for mime type? Because currently it encoded in image-type-specific directory in directory-specific tag, AFAIK.

**Comment by Pitometsu** [comment] 2018-11-30 20:31
E. g. https://github.com/drewnoakes/metadata-extractor/search?q=public+static+final+int+TAG_IMAGE_WIDTH&unscoped_q=public+static+final+int+TAG_IMAGE_WIDTH

**Comment by drewnoakes** [comment] 2019-08-23 02:40
Duplicate of #10.

**Closed by drewnoakes** 2019-08-23 02:40 UTC
