### ISSUE TITLE
NPE in Metadata.readMetadata() - QuickTimeReader

### ISSUE THREAD

**Issue by jchblsc** [drewnoakes/metadata-extractor#318] opened 2018-01-15 17:41 UTC
I get a NullPointerException while executing Metadata.readMetadata().  

`Exception in thread "main" java.lang.NullPointerException
	at com.drew.metadata.mov.metadata.QuickTimeDataHandler.processData(QuickTimeDataHandler.java:105)
	at com.drew.metadata.mov.metadata.QuickTimeDataHandler.processAtom(QuickTimeDataHandler.java:73)
	at com.drew.imaging.quicktime.QuickTimeReader.processAtoms(QuickTimeReader.java:60)
	at com.drew.imaging.quicktime.QuickTimeReader.processAtoms(QuickTimeReader.java:58)
	at com.drew.imaging.quicktime.QuickTimeReader.processAtoms(QuickTimeReader.java:58)
	at com.drew.imaging.quicktime.QuickTimeReader.processAtoms(QuickTimeReader.java:58)
	at com.drew.imaging.quicktime.QuickTimeReader.processAtoms(QuickTimeReader.java:58)
	at com.drew.imaging.quicktime.QuickTimeReader.processAtoms(QuickTimeReader.java:58)
	at com.drew.imaging.quicktime.QuickTimeReader.extract(QuickTimeReader.java:44)
	at com.drew.imaging.quicktime.QuickTimeMetadataReader.readMetadata(QuickTimeMetadataReader.java:54)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:172)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:121)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:197)
	at jch.picsync.MDError.main(MDError.java:16)
`

I've attached the file causing the error below.  This is a Quicktime file that originally had a .MOV filetype.  This is NOT really a JPG!  GitHub is preventing me from uploading as a .MOV - it indicates that it is an unsupported file type.  So I renamed to JPG.  

![img_0038](https://user-images.githubusercontent.com/27036932/34954955-a92765fc-f9df-11e7-9b14-e49a61990357.JPG)

Using metadata-extractor-2.11.0.jar, xmpcore-5.1.3.jar. Don't have any JUNIT in the classpath.  Windows 7.

**Comment by jchblsc** [comment] 2018-01-15 17:42
Using metadata-extractor-2.11.0.jar, xmpcore-5.1.3.jar.  Don't have any JUNIT in the classpath.

**Comment by PaytonGarland** [comment] 2018-01-17 18:50
The cause of this issue seems to be an unknown metadata key: `com.apple.quicktime.camera.identifier`.  We need a better way of handling these unknown keys as there does not seem to be (from what I have found) a finite list from Apple.  Currently, we need to have an integer assigned to each directory entry, which doesn't work for cases like this.  One option would be storing all the data from the metadata atom in a single directory entry (as a list).  Another option would be to assign all unknown metadata entries to a single directory entry (as a list) and then slowly build up our list of known entries.

**Comment by payton** [comment] 2019-01-10 18:35
Fixed in #331

**Closed by payton** 2019-01-10 18:35 UTC
