### ISSUE TITLE
metadata-extractor

### ISSUE THREAD

**Issue by qiuban007** [drewnoakes/metadata-extractor#671] opened 2024-07-10 09:48 UTC
(Please include as much information as possible, and attach a sample image if possible.)
Can the metadata extractor project support the acquisition of FLIR data? Currently, when using metadata extractor to read FLIR jpeg images, there is no Flir data label in the metadata. I see that your metadata extractor dotnet
The project already supports FLIR data acquisition, but it does not support the use of Java. When can FLIR support be added
![image](https://github.com/drewnoakes/metadata-extractor/assets/137995920/915700b3-8d2d-41f1-b354-5c09ef2e409a)

**Comment by drewnoakes** [comment] 2024-07-24 01:56
Duplicate of #197 

In particular: https://github.com/drewnoakes/metadata-extractor/issues/197#issuecomment-855552289

**Closed by drewnoakes** 2024-07-24 01:56 UTC

**Comment by qiuban007** [comment] 2024-07-25 03:25
> #197的重复[](https://github.com/drewnoakes/metadata-extractor/issues/197)
> 
> 特别是：[#197（评论）](https://github.com/drewnoakes/metadata-extractor/issues/197#issuecomment-855552289)

I saw the answer to # 197, but it seems that my requirements are different. My pictures contain FLIR data, and I see that the current library does not support FlirReader, only in NET libraries are supported, but our project uses Java. Do you have any plans to support FlirReader in this library

**Comment by drewnoakes** [comment] 2024-07-25 11:56
Issue 197 is tracking bringing FLIR support from .NET to Java.

If you want to try adding this, feel free to make a pull request.

**Comment by qiuban007** [comment] 2024-07-29 02:11
> Issue 197 is tracking bringing FLIR support from .NET to Java.
> 
> If you want to try adding this, feel free to make a pull request.
ok, thank you
