### ISSUE TITLE
Maker note issue / or skip broken tags...

### ISSUE THREAD

**Issue by sqlboy** [drewnoakes/metadata-extractor#169] opened 2016-04-14 21:57 UTC
Would be great if readMetadata allowed you to skip over broken tags.  I have a couple images where I get this.  Looks its trying to cast a long to an int.   Its great that its an error but now I get no tags, and I'd like to get at least some tags.

Unable to extract EXIF metadata from /Volumes/Seagate Backup Plus Drive/broken/13819169694_a14574242d_o.jpg,[J cannot be cast to [I

```
Caused by: java.lang.ClassCastException: [J cannot be cast to [I
	at com.drew.metadata.exif.makernotes.CanonMakernoteDirectory.setObjectArray(CanonMakernoteDirectory.java:693) ~[metadata-extractor-2.9.0.jar:2.9.0]
	at com.drew.metadata.tiff.DirectoryTiffHandler.setInt32uArray(DirectoryTiffHandler.java:190) ~[metadata-extractor-2.9.0.jar:2.9.0]
	at com.drew.imaging.tiff.TiffReader.processTag(TiffReader.java:372) ~[metadata-extractor-2.9.0.jar:2.9.0]
	at com.drew.imaging.tiff.TiffReader.processIfd(TiffReader.java:228) ~[metadata-extractor-2.9.0.jar:2.9.0]
	at com.drew.metadata.exif.ExifTiffHandler.processMakernote(ExifTiffHandler.java:276) ~[metadata-extractor-2.9.0.jar:2.9.0]
	at com.drew.metadata.exif.ExifTiffHandler.customProcessTag(ExifTiffHandler.java:145) ~[metadata-extractor-2.9.0.jar:2.9.0]
	at com.drew.imaging.tiff.TiffReader.processIfd(TiffReader.java:226) ~[metadata-extractor-2.9.0.jar:2.9.0]
	at com.drew.imaging.tiff.TiffReader.processIfd(TiffReader.java:220) ~[metadata-extractor-2.9.0.jar:2.9.0]
	at com.drew.imaging.tiff.TiffReader.processTiff(TiffReader.java:78) ~[metadata-extractor-2.9.0.jar:2.9.0]
	at com.drew.metadata.exif.ExifReader.extract(ExifReader.java:89) ~[metadata-extractor-2.9.0.jar:2.9.0]
```

**Comment by sqlboy** [comment] 2016-04-14 22:06
Image with the issue:
https://farm8.staticflickr.com/7084/13819169694_a14574242d_o.jpg

**Comment by drewnoakes** [comment] 2016-04-14 22:09
Thanks for the report. Shouldn't be too hard to fix.

Are you willing and able to provide that image to the test data set?

https://github.com/drewnoakes/metadata-extractor-images

**Comment by sqlboy** [comment] 2016-04-14 22:18
Its not really my image, its from Flickr, not sure who it belongs to and the EXIF has no useful copyright data.

What would be nice is a mode where the broken tags are returned as broken tags rather than propagating the exception out to the caller who basically has no way to recover from an individual tag parse failure. 

```
Metadata metadata = ImageMetadataReader.readMetadata(asset.getInputStream());
List<Tag> brokenTags =- metadata.getTagParseFailures();
```

That way, I can note to the users that some tags failed to parse.

**Comment by drewnoakes** [comment] 2016-04-14 22:22
What you're describing is what's supposed to happen, although errors are reported as a set of strings not tags. This exception is a bug. It's also a duplicate of #116, so I'll close this one here.

**Closed by drewnoakes** 2016-04-14 22:22 UTC

**Comment by drewnoakes** [comment] 2016-04-20 23:29
See 86443466944c99bf61ff23375acf642b6d9f2446.
