### ISSUE TITLE
Metadata Extraction gets stuck 

### ISSUE THREAD

**Issue by bin01** [drewnoakes/metadata-extractor#187] opened 2016-07-12 22:52 UTC
We observed that metadata extraction gets stuck when extracting the metadata for the attached image [Blank.png.zip](https://github.com/drewnoakes/metadata-extractor/files/360399/Blank.png.zip). Note: I had to compress it

Here is the stacktrace of the process when its in this state:

> "main" prio=5 tid=0x00007fba23806000 nid=0x1703 runnable [0x0000700000217000]
>    java.lang.Thread.State: RUNNABLE
>     at java.lang.String.equals(String.java:993)
>     at com.adobe.xmp.impl.XMPNode.find(XMPNode.java:882)
>     at com.adobe.xmp.impl.XMPNode.findChildByName(XMPNode.java:232)
>     at com.adobe.xmp.impl.XMPNode.assertChildNotExisting(XMPNode.java:899)
>     at com.adobe.xmp.impl.XMPNode.addChild(XMPNode.java:133)
>     at com.adobe.xmp.impl.ParseRDF.addChildNode(ParseRDF.java:1051)
>     at com.adobe.xmp.impl.ParseRDF.rdf_LiteralPropertyElement(ParseRDF.java:620)
>     at com.adobe.xmp.impl.ParseRDF.rdf_PropertyElement(ParseRDF.java:460)
>     at com.adobe.xmp.impl.ParseRDF.rdf_PropertyElementList(ParseRDF.java:296)
>     at com.adobe.xmp.impl.ParseRDF.rdf_NodeElement(ParseRDF.java:177)
>     at com.adobe.xmp.impl.ParseRDF.rdf_ResourcePropertyElement(ParseRDF.java:568)
>     at com.adobe.xmp.impl.ParseRDF.rdf_PropertyElement(ParseRDF.java:455)
>     at com.adobe.xmp.impl.ParseRDF.rdf_PropertyElementList(ParseRDF.java:296)
>     at com.adobe.xmp.impl.ParseRDF.rdf_NodeElement(ParseRDF.java:177)
>     at com.adobe.xmp.impl.ParseRDF.rdf_NodeElementList(ParseRDF.java:136)
>     at com.adobe.xmp.impl.ParseRDF.rdf_RDF(ParseRDF.java:108)
>     at com.adobe.xmp.impl.ParseRDF.parse(ParseRDF.java:90)
>     at com.adobe.xmp.impl.XMPMetaParser.parse(XMPMetaParser.java:85)
>     at com.adobe.xmp.XMPMetaFactory.parseFromString(XMPMetaFactory.java:130)
>     at com.adobe.xmp.XMPMetaFactory.parseFromString(XMPMetaFactory.java:114)
>     at com.drew.metadata.xmp.XmpReader.extract(XmpReader.java:163)
>     at com.drew.metadata.xmp.XmpReader.extract(XmpReader.java:147)
>     at com.drew.imaging.png.PngMetadataReader.processChunk(PngMetadataReader.java:203)
>     at com.drew.imaging.png.PngMetadataReader.readMetadata(PngMetadataReader.java:87)
>     at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:126)
>     at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:162)
>     at com.shn.contentparser.autonomy.AutonomyExtractor.getXmpMetadata(AutonomyExtractor.java:249)
>     at com.shn.contentparser.autonomy.AutonomyExtractor.extract(AutonomyExtractor.java:137)
>     at com.shn.contentparser.autonomy.AutonomyExtractor.extract(AutonomyExtractor.java:96)
>     at com.shn.contentparser.autonomy.AutonomyContentParser.parse(AutonomyContentParser.java:51)
>     at com.shn.contentparser.autonomy.AutonomyContentParserTest.testInvalidFileFile(AutonomyContentParserTest.java:275)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:606)
>     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
>     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
>     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
>     at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
>     at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
>     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
>     at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:395)
>     at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:371)
>     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
>     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
>     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
>     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
>     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
>     at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
>     at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
>     at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
>     at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
>     at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
>     at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
>     at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by drewnoakes** [comment] 2016-07-13 04:21
Can you attach an image that reproduces this issue? It looks like a problem
in Adobe's XMP library.

**Comment by bin01** [comment] 2016-07-13 04:53
I already did. Could you click on Blank.png.zip?

**Comment by drewnoakes** [comment] 2016-07-13 22:49
You're right, I missed that.

The file contains 21MB of XMP data. That's considerably more than I've ever seen before.

What you've discovered isn't a deadlock or crash, it's a performance issue with the Adobe XMP library used by this project.

I can't find an issue tracker for the Adobe XMPCore project anywhere, nor a repo that accepts PRs.

**Comment by tballison** [comment] 2016-10-13 15:55
Still happens with 6.1.10.  I'll see if I can find any POCs who might be able to help.

**Comment by drewnoakes** [comment] 2016-11-12 23:05
Closing as this is technically a problem with XMPCore.

**Closed by drewnoakes** 2016-11-12 23:05 UTC
