### ISSUE TITLE
Unable to detect mp3 files

### ISSUE THREAD

**Issue by adholland** [drewnoakes/metadata-extractor#545] opened 2021-07-12 14:38 UTC
Currently using 2.16.0 version of metadata-extractor. Ability to detect the file types works as expected other than mp3 files. I've attempted to detected numerous different mp3 files without success, with the library returning an 'Unknown' file type.

The following image shows the intial mp3 bytes via intellij: -
![image](https://user-images.githubusercontent.com/27013642/125309488-b7198780-e329-11eb-8cd2-c34908108af9.png)

this from another mp3 file: -
![image](https://user-images.githubusercontent.com/27013642/125309597-cc8eb180-e329-11eb-9c77-7223900551fc.png)

**Comment by adholland** [comment] 2021-07-12 14:42
@drewnoakes please advise on the above issue. I've taken the latest version hoping this would resolve the issue, but unfortunately it still seems that the library is unable to detect mp3 files.

**Comment by payton** [comment] 2021-07-17 23:09
@adholland, in addition to the screenshots/beginning bytes, it would be helpful if you could provide a sample file to reproduce this with.

**Comment by drewnoakes** [comment] 2021-07-20 21:25
It looks like these are MP3 files with leading ID3 data, which is not currently supported. There's another issue tracking ID3 support I believe (on a phone right now).

**Comment by payton** [comment] 2021-07-20 22:41
Ah, right #328

**Comment by payton** [comment] 2021-07-20 22:42
Will close this as a duplicate.

To reiterate, this request is being tracked in #328

The file is not being identified as an MP3 due to leading ID3 data.

**Closed by payton** 2021-07-20 22:42 UTC
Labels: format-mp3, status-duplicate
