### ISSUE TITLE
How to test against the images database?

### ISSUE THREAD

**Issue by nathanaeljones** [drewnoakes/metadata-extractor#110] opened 2015-06-03 00:41 UTC
Is there an automated way to test MetadataExtractor against the metadata-extractor-images repository? All unit tests pass in the [C# port](https://github.com/drewnoakes/metadata-extractor), but I'm seeing some regressions on certain images where only the basic jpeg directory is available, and all (more sophisticated) directories are missing. 

An example: 

https://raw.githubusercontent.com/drewnoakes/metadata-extractor-images/master/jpg/FujiFilm%20FinePix2650.jpg

**Comment by Odrahcyr** [comment] 2015-06-03 05:52
No but #64 will add this feature. I already did some work on #64,  maybe I will use this weekend to complete it.

**Comment by drewnoakes** [comment] 2015-06-03 14:47
My current approach is to run the lib across the database and use Git to track any changes. This has been very useful in catching regressions, as well as validating how useful/far reaching changes have been.

This became a little tougher when file-system metadata was added, as that differs per checkout of the repo, so I'm inclined to remove that section from the text files.

**Comment by nathanaeljones** [comment] 2015-06-03 15:42
What commands do you use to execute the library? I'd like to establish a baseline for 2.8.0, so I can narrow down the source of the problem.  It's quite possible the automated source conversion missed an edge case, but given that almost half of the jpegs parse correctly, and the other half just have missing directories, it smells like a rather subtle bug.

**Comment by drewnoakes** [comment] 2015-06-03 15:48
Something like:

    java -jar com.drew.tools.ProcessAllImagesInFolderUtility -text "/path/root/for/search"

See [this source file](https://github.com/drewnoakes/metadata-extractor/blob/master/Source/com/drew/tools/ProcessAllImagesInFolderUtility.java) to see what's going on.

It walks recursively, looking for certain file types, parses them and writes into the `metadata/` subfolder a file with the same name, ending in `.txt`, IIRC.

**Comment by nathanaeljones** [comment] 2015-06-03 15:57
How are you building that jar?

**Comment by drewnoakes** [comment] 2015-06-03 16:38
Sorry, no need for the -jar option.

**Comment by nathanaeljones** [comment] 2015-06-03 20:28
Using `java -cp ./Output/maven/classes com.drew.tools.ProcessAllImagesInFolderUtility -text "/Users/nathanael/Documents/delete/metadata-extractor-images/"`, I get errors for most images, -> `Could not initialize class com.drew.imaging.jpeg.JpegMetadataReader`. Using 65623d2b172ae81b0d8502dfa1514f9782067bcb

I'm rolling back to 2.8.0 to give that a try.

**Comment by drewnoakes** [comment] 2015-06-04 09:30
The underlying exception in this case is because Adobe's XMPCore JAR file is not on the classpath and therefore was not found.

**Comment by nathanaeljones** [comment] 2015-06-04 11:51
Thanks! I didn't catch that. 

This worked: 
`java -cp ./Libraries/*:./Output/maven/classes com.drew.tools.ProcessAllImagesInFolderUtility -text "/Users/nathanael/Documents/delete/metadata-extractor-images/"`

**Comment by drewnoakes** [comment] 2015-06-29 18:58
Are you happy for me to close this now?

FYI I'm working on getting the Java and [.NET implemenation](https://github.com/drewnoakes/metadata-extractor-dotnet) to produce identical output over the image database. It's close, but there are a few tricky differences left -- mostly just that C#/.NET has a richer set of primitive types that map better to those used in Exif and other formats (such as unsigned integers) which Java doesn't have, and which then cause differences in output. I'm tracking these in [issues against the .NET project](https://github.com/drewnoakes/metadata-extractor-dotnet/issues) for now.

**Closed** 2015-06-29 23:00 UTC
