### ISSUE TITLE
Support for HEIF/HEIC files

### ISSUE THREAD

**Issue by emanueldejanu** [drewnoakes/metadata-extractor#313] opened 2017-12-29 12:46 UTC
Please add support for heif container (I'm interested to read heic files metadata)?

http://nokiatech.github.io/heif/
https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format

Thanks,

Emanuel

**Comment by drewnoakes** [comment] 2017-12-29 13:20
Agree it would be cool. Closing this as a duplicate of #310.

**Closed by drewnoakes** 2017-12-29 13:20 UTC
