### ISSUE TITLE
How to write XMP metadata back to Image

### ISSUE THREAD

**Issue by rvankayala** [drewnoakes/metadata-extractor#277] opened 2017-07-10 09:33 UTC
(Please include as much information as possible, and attach a sample image if possible.)
I have a XMP metadata information and want to add back to the newly created image.

Unable to find out a way to do that.

Can you help me. Looking out code sample in java

**Comment by PaytonGarland** [comment] 2017-07-10 21:20
This library is intended for reading metadata from images versus actually writing to them.  There is an XmpWriter class that serializes the XMPMeta object into an output stream, but it does not replace what was in the image.

In this example, I am just modifying the SharpenEdgeMasking property:
```
try {
    XmpWriter xmpWriter = new XmpWriter();

    XmpDirectory directory = metadata.getFirstDirectoryOfType(XmpDirectory.class);

    XMPMeta xmpMeta = directory.getXMPMeta();

    xmpMeta.setPropertyInteger("http://ns.adobe.com/camera-raw-settings/1.0/", "SharpenEdgeMasking", 10);

    OutputStream outputStream = new FileOutputStream(new File("example.xml"));

    xmpWriter.write(outputStream, metadata);
} catch (XMPException e) {
    e.printStackTrace();
}
```
The metadata object used is from reading the metadata from [this](https://github.com/drewnoakes/metadata-extractor-images/blob/master/jpg/Issue%20266.jpg) image.  After you have the output stream, it's just a matter of replacing it with the XMP data in the file, but I do not have experience with that.  Maybe someone else here has more experience or knows of another tool that could help.

**Comment by rvankayala** [comment] 2017-07-11 07:13
Actually my requirement is that, we have a images with lot of XMP data. While image upload, we are using ImageMagic tool for compressing the uploaded image. This will create a brand new image with compressed in size.

So, after compression XMP metadata is lost. So our requirement is that, we need to read XMP metadata before compression. So that after image has been compressed, we need to apply back the XMP metadata to image.

**Comment by PaytonGarland** [comment] 2017-07-11 14:30
@rvankayala No problem.  

If you need to read the data beforehand, you can use what I showed you earlier, but the XmpDirectory would come from the metadata object that was returned from reading your uncompressed image.  Then you can save what was in the output stream for inserting into the image later.

Unfortunately I won't be much help with applying it back to the compressed image as I have not had experience with this.

**Comment by drewnoakes** [comment] 2020-05-11 04:33
Closing as a duplicate of #14.

**Closed by drewnoakes** 2020-05-11 04:33 UTC
